
import javax.swing.JFrame;
import javax.swing.ImageIcon;
//import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author E-rinGZ
 */
public class HomePage extends javax.swing.JFrame {
        // ImageIcon icon;
       //  String message = "Colegio De Montalban";
    /**
     * Creates new form HomePage
     */
    
         
    public HomePage() {
        setUndecorated(true);
        initComponents();
        setVisible(true); 
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setBounds(462,220,754,580);
       // icon = new ImageIcon("image/cdmlogocrop.jpg");
       // setTitle (message);
      //  setIconImage(icon.getImage());
      //  Container con = getContentPane();
       // con.setBackground(Color.green);
        
        setResizable(false);
        
        //setSize (780, );
    }  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        head = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        attendance = new javax.swing.JLabel();
        Log = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        schoolBackground = new javax.swing.JLabel();
        cdmlogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        admin = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusableWindowState(false);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(6, 51, 21));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        head.setBackground(new java.awt.Color(15, 68, 46));
        head.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setBackground(new java.awt.Color(7, 54, 38));
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-close-window-24.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMousePressed(evt);
            }
        });
        close.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                closeKeyPressed(evt);
            }
        });
        head.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 0, -1, 25));

        attendance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        attendance.setForeground(new java.awt.Color(199, 218, 225));
        attendance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        attendance.setText("ATTENDANCE SYSTEM");
        head.add(attendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        body.add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 756, -1));

        Log.setBackground(new java.awt.Color(23, 253, 94));
        Log.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Log.setForeground(new java.awt.Color(9, 91, 66));
        Log.setText("LOG ");
        Log.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogMouseExited(evt);
            }
        });
        Log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogActionPerformed(evt);
            }
        });
        body.add(Log, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 200, 48));

        jButton2.setBackground(new java.awt.Color(7, 45, 33));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("REGISTER");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        body.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 200, 30));

        schoolBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/schoolback.jpg"))); // NOI18N
        body.add(schoolBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 480, 580));

        cdmlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo 2.jpg"))); // NOI18N
        body.add(cdmlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 210, 190));

        jPanel2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel2PropertyChange(evt);
            }
        });

        admin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/admin.png"))); // NOI18N
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                adminMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(admin, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(admin, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        body.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, 90, 80));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background16.jpg"))); // NOI18N
        body.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 760, 560));

        getContentPane().add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed
        System.exit(0);
    }//GEN-LAST:event_closeMousePressed

    private void closeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_closeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_closeKeyPressed

    private void jPanel2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel2PropertyChange
        jPanel2.setBackground(new java.awt.Color(0,0,0,0));               
    }//GEN-LAST:event_jPanel2PropertyChange

    private void adminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMousePressed
        new adminLog().setVisible(true);
        this.setVisible(false);      
    }//GEN-LAST:event_adminMousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new studentRegisterForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        //this.setForeground(new Color (0,0,0));
    }//GEN-LAST:event_jButton2MouseExited

    private void LogMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogMouseExited
       //this.setForeground(new Color (0,0,0));
    }//GEN-LAST:event_LogMouseExited

    private void LogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogActionPerformed
        new usersLog().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Log;
    private javax.swing.JLabel admin;
    private javax.swing.JLabel attendance;
    private javax.swing.JLabel background;
    private javax.swing.JPanel body;
    private javax.swing.JLabel cdmlogo;
    private javax.swing.JLabel close;
    private javax.swing.JPanel head;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel schoolBackground;
    // End of variables declaration//GEN-END:variables

    private void setOpaque(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setContentAreaFilled(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setBorderPainted(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
