
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author E-rinGZ
 */
public class studentDatabase extends javax.swing.JFrame {

    /**
     * Creates new form studentDatabase
     */
    Connection myconObj=null;
    Statement mystatObj=null;
    ResultSet myresObj=null;
    
    public studentDatabase() {
        initComponents();
        connect();
    }
public void connect(){
        try{
        myconObj=DriverManager.getConnection("jdbc:derby://localhost:1527/studentregistraion", "ron", "123456789");
        mystatObj=myconObj.createStatement();
        myresObj=mystatObj.executeQuery("Select * from ron.studentinfo");
        studentTable.setModel(DbUtils.resultSetToTableModel(myresObj)); 
        }
        catch(SQLException e){
            e.printStackTrace();
        }
}  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        ok = new javax.swing.JButton();
        sample = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "studentno", "password", "lastname", "firstname", "middlename", "email", "contact", "course", "address"
            }
        ));
        jScrollPane1.setViewportView(studentTable);

        ok.setText("DELETE");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        sample.setText("ENTER STUDENT NO");

        jLabel1.setText("INFORMATION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ok)
                .addGap(319, 319, 319))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(sample, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(sample, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ok)
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        /*int row =studentTable.getSelectedRow();
        System.out.println(row);
        String cell =studentTable.getModel().getValueAt(row,0).toString();
        String sql ="DELETE * FROM ron.untitled WHERE studentno= "+cell;
         Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/studentregistraion", "ron", "123456789");*/
         
       /* try{
            String sql ="DELETE  FROM ron.studentinfo WHERE studentno= "+sample.getText();
            Statement add = myconObj.createStatement();
            add.executeUpdate(sql);
                    }catch(SQLException e){
            e.printStackTrace(); 
            
        }connect();*/
            
       //int enter =Integer.parseInt(sample.getText());
        
        try{
            
            String sql ="DELETE  FROM ron.studentinfo WHERE studentno="+sample.getText();
            Statement add = myconObj.createStatement();
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/studentregistraion", "ron", "123456789");
           // Statement add = con.prepareStatement(sql);
            add.executeUpdate(sql);
            /*ResultSet rs = add.executeQuery(sql);
            if(rs.next()){
                String lastname = rs.getString(3);
                String firstname = rs.getString(4);
                String middlename = rs.getString(5);
                //String course = rs.getString(8);
                String fullname = lastname + " , " +firstname +" " +middlename;
                jLabel1.setText(fullname);
                //section.setText(course);
            }*/
                   
        }catch(SQLException e){
            e.printStackTrace(); 
          jLabel1.setText("Plese Check");
        }
        connect();
    }//GEN-LAST:event_okActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentDatabase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ok;
    private javax.swing.JTextField sample;
    private javax.swing.JTable studentTable;
    // End of variables declaration//GEN-END:variables
}
