
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author E-rinGZ
 */
public class studentRegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form studentRegisterForm
     */
    JComboBox comboBox;
    Connection myconObj= null;
        Statement mystatObj=null;
        ResultSet myresObj=null;
    public studentRegisterForm() {
        initComponents();
        jPanel1.setFocusable(true);
        ilabas.setVisible(false);
        mali.setVisible(false);
        mali1.setVisible(false);
         connect(); 
       
            
    }
 public void connect(){
        try{
        myconObj=DriverManager.getConnection("jdbc:derby://localhost:1527/studentregistraion", "ron", "123456789");
        mystatObj=myconObj.createStatement();
        myresObj=mystatObj.executeQuery("Select * from ron.studentinfo");
        }
        catch(SQLException e){
            e.printStackTrace();
        }
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        mali1 = new javax.swing.JLabel();
        mali = new javax.swing.JLabel();
        gitna = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        studentNO = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        itago = new javax.swing.JLabel();
        ilabas = new javax.swing.JLabel();
        passWord = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        pangalan = new javax.swing.JTextField();
        apelido = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        sumite = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        course = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(1, 32, 1));
        jLabel9.setText("TIRAHAN");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 90, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(1, 32, 1));
        jLabel5.setText("PANGALAN");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 90, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("REHISTRASYON");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 650, 50));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 290, 10));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 290, 10));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 370, 10));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 370, 10));

        jSeparator5.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jSeparator5PropertyChange(evt);
            }
        });
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 370, 30));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 120, 20));

        mali1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mali1.setForeground(new java.awt.Color(204, 0, 0));
        mali1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1x/errorAsset 2.png"))); // NOI18N
        mali1.setText("MAHALAGANG TAMA ANG ID NO");
        jPanel2.add(mali1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 250, 20));

        mali.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mali.setForeground(new java.awt.Color(204, 0, 0));
        mali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1x/errorAsset 2.png"))); // NOI18N
        mali.setText("NAGAMIT NA ANG STUDENT NO");
        jPanel2.add(mali, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 250, 20));

        gitna.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        gitna.setForeground(new java.awt.Color(153, 153, 153));
        gitna.setText("GITNA");
        gitna.setBorder(null);
        gitna.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                gitnaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                gitnaFocusLost(evt);
            }
        });
        gitna.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                gitnaPropertyChange(evt);
            }
        });
        jPanel2.add(gitna, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 100, 40));

        contact.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        contact.setForeground(new java.awt.Color(1, 32, 1));
        contact.setBorder(null);
        contact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contactFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                contactFocusLost(evt);
            }
        });
        contact.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                contactPropertyChange(evt);
            }
        });
        contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contactKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactKeyTyped(evt);
            }
        });
        jPanel2.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 370, 40));

        email.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        email.setForeground(new java.awt.Color(1, 32, 1));
        email.setBorder(null);
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        email.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                emailPropertyChange(evt);
            }
        });
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 370, 40));

        studentNO.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        studentNO.setForeground(new java.awt.Color(153, 153, 153));
        studentNO.setText("1900937");
        studentNO.setBorder(null);
        studentNO.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                studentNOFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                studentNOFocusLost(evt);
            }
        });
        studentNO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                studentNOMousePressed(evt);
            }
        });
        studentNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentNOActionPerformed(evt);
            }
        });
        studentNO.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                studentNOPropertyChange(evt);
            }
        });
        studentNO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                studentNOKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                studentNOKeyTyped(evt);
            }
        });
        jPanel2.add(studentNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 280, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(1, 32, 1));
        jLabel7.setText("PASSWORD");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 110, 40));

        itago.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        itago.setForeground(new java.awt.Color(39, 87, 34));
        itago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itago.setText("ITAGO");
        itago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                itagoMousePressed(evt);
            }
        });
        jPanel2.add(itago, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 60, 20));

        ilabas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ilabas.setForeground(new java.awt.Color(39, 87, 34));
        ilabas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ilabas.setText("ILABAS");
        ilabas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ilabasMousePressed(evt);
            }
        });
        jPanel2.add(ilabas, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 60, 20));

        passWord.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        passWord.setForeground(new java.awt.Color(153, 153, 153));
        passWord.setText("PASSWORDMO?");
        passWord.setBorder(null);
        passWord.setEchoChar('\u0398');
        passWord.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passWordFocusGained(evt);
            }
        });
        passWord.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                passWordPropertyChange(evt);
            }
        });
        jPanel2.add(passWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 280, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(1, 32, 1));
        jLabel8.setText("STUDENT NO");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 110, 40));

        pangalan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pangalan.setForeground(new java.awt.Color(153, 153, 153));
        pangalan.setText("PANGALAN");
        pangalan.setBorder(null);
        pangalan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pangalanFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pangalanFocusLost(evt);
            }
        });
        pangalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pangalanActionPerformed(evt);
            }
        });
        pangalan.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                pangalanPropertyChange(evt);
            }
        });
        jPanel2.add(pangalan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 150, 40));

        apelido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        apelido.setForeground(new java.awt.Color(153, 153, 153));
        apelido.setText("APELIDO");
        apelido.setBorder(null);
        apelido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                apelidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                apelidoFocusLost(evt);
            }
        });
        apelido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apelidoActionPerformed(evt);
            }
        });
        apelido.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                apelidoPropertyChange(evt);
            }
        });
        jPanel2.add(apelido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 120, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(1, 32, 1));
        jLabel10.setText("EMAIL ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 90, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(1, 32, 1));
        jLabel11.setText("COURSE ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 90, 40));

        address.setColumns(20);
        address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        address.setForeground(new java.awt.Color(1, 32, 1));
        address.setRows(5);
        address.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setViewportView(address);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 370, 150));

        sumite.setBackground(new java.awt.Color(46, 108, 76));
        sumite.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sumite.setForeground(new java.awt.Color(21, 39, 63));
        sumite.setText("SUMITE");
        sumite.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(48, 95, 55), new java.awt.Color(57, 127, 34), new java.awt.Color(27, 60, 40), new java.awt.Color(51, 94, 26)));
        sumite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumiteActionPerformed(evt);
            }
        });
        jPanel2.add(sumite, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 110, 30));

        jLabel12.setBackground(new java.awt.Color(33, 38, 52));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(43, 48, 64));
        jLabel12.setText("PINDUTIN ANG LOGO UPANG MAKABALIK SA HOMEPAGE");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 440, -1));

        jLabel13.setBackground(new java.awt.Color(33, 38, 52));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(43, 48, 64));
        jLabel13.setText("PAUNAWA: ");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(1, 32, 1));
        jLabel14.setText("CONTACT");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 90, 40));

        course.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSCPE 2A" }));
        course.setBorder(null);
        course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseActionPerformed(evt);
            }
        });
        course.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                coursePropertyChange(evt);
            }
        });
        jPanel2.add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 110, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/formbackground1.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 540));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1x/errorAsset 2.png"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 650, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1x/asset2.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/headbackground2.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registerbackground1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void studentNOPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_studentNOPropertyChange
        studentNO.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_studentNOPropertyChange

    private void studentNOFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studentNOFocusGained
        if(studentNO.getText().trim().equals("1900937")){
            studentNO.setText(null);
            studentNO.setForeground(new Color(1,32,1));          
        }
        
    }//GEN-LAST:event_studentNOFocusGained

    private void studentNOFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studentNOFocusLost
        if(studentNO.getText().trim().equals("")){
            studentNO.setText("1900937");
            studentNO.setForeground(new Color(153,153,153));          
        }
    }//GEN-LAST:event_studentNOFocusLost

    private void passWordPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_passWordPropertyChange
        passWord.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_passWordPropertyChange

    private void apelidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apelidoFocusGained
          if(apelido.getText().trim().toUpperCase().equals("APELIDO")){
            apelido.setText(null);
            apelido.setForeground(new Color(1,32,1));          
        }
    }//GEN-LAST:event_apelidoFocusGained

    private void apelidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apelidoFocusLost
         if(apelido.getText().trim().equals("")){
            apelido.setText("APELIDO");
            apelido.setForeground(new Color(153,153,153));          
        }
    }//GEN-LAST:event_apelidoFocusLost

    private void apelidoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_apelidoPropertyChange
        apelido.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_apelidoPropertyChange

    private void apelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apelidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apelidoActionPerformed

    private void pangalanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pangalanFocusGained
        if(pangalan.getText().trim().equals("PANGALAN")){
            pangalan.setText(null);
            pangalan.setForeground(new Color(1,32,1)); 
        }    
    }//GEN-LAST:event_pangalanFocusGained
    
    private void pangalanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pangalanFocusLost
       if(pangalan.getText().trim().equals("")){
            pangalan.setText("PANGALAN");
            pangalan.setForeground(new Color(153,153,153)); 
        }     
    }//GEN-LAST:event_pangalanFocusLost

    private void pangalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pangalanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pangalanActionPerformed

    private void pangalanPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_pangalanPropertyChange
        pangalan.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_pangalanPropertyChange

    private void gitnaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gitnaFocusGained
           if(gitna.getText().trim().equals("GITNA")){
            gitna.setText(null);
            gitna.setForeground(new Color(1,32,1)); 
        } 
    }//GEN-LAST:event_gitnaFocusGained

    private void gitnaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gitnaFocusLost
           if(gitna.getText().trim().equals("")){
            gitna.setText("GITNA");
            gitna.setForeground(new Color(153,153,153)); 
        } 
    }//GEN-LAST:event_gitnaFocusLost

    private void gitnaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_gitnaPropertyChange
        gitna.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_gitnaPropertyChange

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFocusGained

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFocusLost

    private void emailPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_emailPropertyChange
        email.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_emailPropertyChange

    private void contactFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_contactFocusGained

    private void contactFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_contactFocusLost

    private void contactPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_contactPropertyChange
        contact.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_contactPropertyChange

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        new HomePage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel4MousePressed

    private void passWordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passWordFocusGained
        if(passWord.getText().equals("PASSWORDMO?")){
            passWord.setText(null);
            passWord.setForeground(new Color(1,32,1)); 
        }
    }//GEN-LAST:event_passWordFocusGained

    private void itagoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itagoMousePressed
        ilabas.setVisible(true);
        itago.setVisible(false);
        passWord.setEchoChar((char)0);
    }//GEN-LAST:event_itagoMousePressed
        
    private void ilabasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ilabasMousePressed
        ilabas.setVisible(false);
        itago.setVisible(true);
        passWord.setEchoChar((char)920);
    }//GEN-LAST:event_ilabasMousePressed

    private void studentNOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentNOMousePressed
     
        
    }//GEN-LAST:event_studentNOMousePressed

    private void jSeparator5PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jSeparator5PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jSeparator5PropertyChange

    private void coursePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_coursePropertyChange
        course.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_coursePropertyChange

    private void studentNOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentNOKeyTyped
        char c = evt.getKeyChar();
        String text = studentNO.getText();   
        if(!Character.isDigit(c)){
            evt.consume();
           
        }
    }//GEN-LAST:event_studentNOKeyTyped

    private void studentNOKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentNOKeyPressed
         String studentnumber = studentNO.getText();
        int length = studentnumber.length();
        char c = evt.getKeyChar();  
        if(length<7)
            if(length<7){
                studentNO.setEditable(true);
            }else{
                studentNO.setEditable(false);
            
            }else{
              if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE|| evt.getExtendedKeyCode()==KeyEvent.VK_DELETE ) {
                    studentNO.setEditable(true);                  
                    }else{
                    studentNO.setEditable(false);
                    }
              }   

    }//GEN-LAST:event_studentNOKeyPressed

    private void contactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactKeyTyped
        char c = evt.getKeyChar();
        String text = studentNO.getText();   
        if(!Character.isDigit(c)){
            evt.consume();
           
        }
    }//GEN-LAST:event_contactKeyTyped

    private void contactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactKeyPressed
        String contactnumber = contact.getText();
        int length = contactnumber.length();
        char c = evt.getKeyChar();  
        if(length<11)
            if(length<11){
                contact.setEditable(true);
            }else{
                contact.setEditable(false);
            
            }else{
              if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE|| evt.getExtendedKeyCode()==KeyEvent.VK_DELETE ) {
                    contact.setEditable(true);                  
                    }else{
                    contact.setEditable(false);
                    }
              }  
    }//GEN-LAST:event_contactKeyPressed

    private void sumiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumiteActionPerformed
            String id = studentNO.getText();
            String password = passWord.getText();
            String lastName = apelido.getText().toUpperCase();
            String firstName = pangalan.getText().toUpperCase();
            String middleName = gitna.getText().toUpperCase();
            String eadd = email.getText();
            String contactNo = contact.getText();
            String section = course.getSelectedItem().toString();
            String addRess = address.getText().toUpperCase();  
            int studentnumber = Integer.parseInt(id);
            int passlength = password.length();
            int lastNamelength = lastName.length();
            int firstNamelength = firstName.length();
            int middleNamelength = middleName.length();
            int eaddlength = eadd.length();
            int contactlength = contactNo.length();
            int addresslength = addRess.length();
             ImageIcon icon = new ImageIcon("cdmlogocrop.jpg");
        JOptionPane.showOptionDialog(null,"Gusto mo bang ituloy?","REHISTRADO", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, icon, null, 0);
             if(studentnumber<1900000||passlength==0||lastNamelength==0||firstNamelength==0||middleNamelength==0||eaddlength==0||contactlength==0||addresslength==0){                                          
       JOptionPane.showMessageDialog(null,"IMBALIDO","ERRORMSN",JOptionPane.ERROR_MESSAGE);
             }else{
                 try{
            PreparedStatement add = myconObj.prepareStatement("insert into ron.studentinfo values(?,?,?,?,?,?,?,?,?)");
            add.setInt(1, studentnumber);
            add.setString(2, password);
            add.setString(3, lastName);
            add.setString(4, firstName);
            add.setString(5, middleName);
            add.setString(6, eadd);
            add.setString(7, contactNo);
            add.setString(8, section );
            add.setString(9, addRess);
            int row = add.executeUpdate();
            JOptionPane.showMessageDialog(null, "MATAGUMPAY NA NAKAREHISTRO", "REHISTRADO",JOptionPane.INFORMATION_MESSAGE);
            studentNO.setText("") ;
            passWord.setText("");
            apelido.setText("");
            pangalan.setText("");
            gitna.setText("");
            email.setText(null);
            contact.setText(null);
            address.setText(null);
        
        }
        catch(SQLException E){
            E.printStackTrace();
            mali.setVisible(true);//NAGAMIT NA ANG STUDENT NO
            mali1.setVisible(false);
        }
              /*  }else{
                JOptionPane.showMessageDialog(null,"IMBALIDO");      
                mali1.setVisible(true);//MAHALAGANG TAMA ANG ID NO
                mali.setVisible(false); */
             }
             
        
    }//GEN-LAST:event_sumiteActionPerformed

    private void courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseActionPerformed

    private void studentNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentNOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentRegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JTextField apelido;
    private javax.swing.JTextField contact;
    private javax.swing.JComboBox<String> course;
    private javax.swing.JTextField email;
    private javax.swing.JTextField gitna;
    private javax.swing.JLabel ilabas;
    private javax.swing.JLabel itago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel mali;
    private javax.swing.JLabel mali1;
    private javax.swing.JTextField pangalan;
    private javax.swing.JPasswordField passWord;
    private javax.swing.JTextField studentNO;
    private javax.swing.JButton sumite;
    // End of variables declaration//GEN-END:variables
}
